[versions]
agp = "9.0.1"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
kotlin = "2.2.10"
composeBom = "2026.02.01"
navigationRuntimeKtx = "2.9.8"
material3 = "1.4.0"
runtime = "1.11.1"
benchmarkTraceprocessor = "1.4.1"